---
- name: Simulate upgrade
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Simulate upgrade
      apt:
        upgrade: safe
        update_cache: yes
        simulate: yes
      register: apt_sim

    - name: Show upgrade simulation results
      debug:
        var: apt_sim.stdout_lines
