---
- name: Check for upgrades
  hosts: all
  become: yes
  tasks:
    - name: Run apt simulate
      command: apt-get upgrade --simulate
      register: apt_sim
      changed_when: false  # This tells Ansible "I didn't actually change anything"

    - name: Show upgrade results
      debug:
        var: apt_sim.stdout_lines
