- name: Check if reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Reboot only if required
  reboot:
    msg: "Reboot triggered by SAFE update"
    pre_reboot_delay: 10
    post_reboot_delay: 30
  when: reboot_required.stat.exists
